all:
  metas:
    title:     fac24 - Products
  components:
    searchForm: [search, productForm]
    
indexSuccess:
  stylesheets: [ /sfFormExtraPlugin/css/jquery.autocompleter.css ]
  javascripts:
    - core/table.js
    
editSuccess:
  javascripts:
    - invoice
