all:
  javascripts: []
settingsSuccess:
  javascripts:
    - siwapp/settings/global.js
    - js-digito-control-calculator/calcularDC.js
productCategoriesSuccess:
  javascripts:
    - siwapp/settings/categories.js
profileSuccess:
  javascripts:
    - siwapp/lang.selector.js

ajaxGetCountriesSuccess:
  has_layout: false
