all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=teixido'
      username: 'siwapp'
      password: 'wappis'

test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=siwapp_test'
      username: 'siwapp'
      password: 'wappis'
