all:
  metas:
    title:     siwapp - Companyies
  components:
    searchForm: [search, companyForm]
    
indexSuccess:
  stylesheets: [ /sfFormExtraPlugin/css/jquery.autocompleter.css ]
  javascripts:
    - core/table.js
editSuccess:
  javascripts:
    - invoice.js

