all:
  metas:
    title:     fac24 - Companyies
  components:
    searchForm: [search, companyForm]

indexSuccess:
  stylesheets: [ /sfFormExtraPlugin/css/jquery.autocompleter.css ]
  javascripts:
    - core/table.js
editSuccess:
  javascripts:
    - invoice.js
    - js-digito-control-calculator/calcularDC.js

